version: '3'

services:
  rss-backend:
    build:
      context: rss-backend/
    ports:
      - 9230:9230
    volumes:
      - ./rss-backend:/app/rss-feed

  redis:
    image: redis:6.0.7-alpine
    ports:
      - 6379:6379
  nginx:
    image: nginx:1.19.2-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
